name: foodgram workflow

on:
  push:
    branches:
      - main

jobs:
  backend-tests:
    name: tests of backend
    runs-on: ubuntu-latest

    steps:
      - name: Clone the rep
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install back requirements
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Format PEP8 with Flake8
        run: |
          cd backend
          pip install flake8
          flake8 . --max-line-length=92

      - name: Backend Tests
        run: |
          cd backend/foodgram
          python manage.py test

  docker-build:
    name: Get up Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Check Build Of Backend
        run: docker build -t foodgram-backend-test ./backend

      - name: Check Build Of Frontend
        run: docker build -t foodgram-frontend-test ./frontend