name: CI Workflow - Foodgram

on:
  push:
    branches:
      - main

jobs:
  backend-tests:
    name: Backend Verification
    runs-on: ubuntu-latest

    steps:
      - name: Fetch repository code
        uses: actions/checkout@v4

      - name: Fetch repository code
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Code style validation (Flake8)
        run: |
          cd backend
          pip install flake8
          flake8 . --max-line-length=92

      - name: Run unit tests
        run: |
          cd backend/foodgram
          python manage.py test

  docker-build:
    name: Docker Image Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Validate Backend Docker Build
        run: docker build -t foodgram-backend-image ./backend

      - name: Validate Frontend Docker Build
        run: docker build -t foodgram-frontend-image ./frontend